function output = main_example()
%MAIN_EXAMPLE Exercise the public two-stage method interface.

repository_root = fileparts(mfilename('fullpath'));
addpath(fullfile(repository_root, 'src'));
addpath(fullfile(repository_root, 'example'));
addpath(fullfile(repository_root, 'config'));

method = method_definition();
example = make_example_input();
validate_inputs(example.X, example.y, example.group_id, example.feature_domain);

selected_index = select_top_k(example.ranking_order, method.top_k);
selected = false(method.total_feature_count, 1);
selected(selected_index) = true;

stage1_index = find(selected & ismember(example.feature_domain, method.stage1.domains));
stage2_index = find(selected & ismember(example.feature_domain, method.stage2.domains));
if isempty(stage1_index) || isempty(stage2_index)
    error('PUBLIC_METHOD_CODE:SelectedDomains', ...
        'The supplied ranking must retain features for both stages.');
end

stage1_model = train_stage1( ...
    example.X(:, stage1_index), example.y, example.run_id);
[stage1_calibrator, stage1_oof_scores] = grouped_oof_calibration( ...
    example.X(:, stage1_index), ...
    stage1_labels(example.y), ...
    example.group_id, example.run_id, method.stage1.classes, ...
    method.stage1.beta_by_class, method.weighting.alpha);

stage2_rows = ismember(string(example.y), method.stage2.classes);
stage2_model = train_stage2( ...
    example.X(stage2_rows, stage2_index), example.y(stage2_rows), ...
    example.run_id(stage2_rows), method.stage2.example_beta_motor);
stage2_beta_by_class = struct( ...
    'NORMAL', 1.0, ...
    'MOTOR_ACTUATOR_FAULT', method.stage2.example_beta_motor, ...
    'POSITION_SENSOR_FAULT', 1.0);
[stage2_calibrator, stage2_oof_scores] = grouped_oof_calibration( ...
    example.X(stage2_rows, stage2_index), example.y(stage2_rows), ...
    example.group_id(stage2_rows), example.run_id(stage2_rows), ...
    method.stage2.classes, stage2_beta_by_class, method.weighting.alpha);

[~, stage1_scores] = predict(stage1_model.classifier, example.X(:, stage1_index));
stage1_probability = apply_logistic_calibration( ...
    stage1_scores, stage1_model.classifier.ClassNames, stage1_calibrator);
[~, stage2_scores] = predict(stage2_model.classifier, example.X(:, stage2_index));
stage2_probability = apply_logistic_calibration( ...
    stage2_scores, stage2_model.classifier.ClassNames, stage2_calibrator);

five_state_probability = hierarchical_probability_fusion( ...
    stage1_probability, stage2_probability);
evaluation = evaluate_five_state(example.y, five_state_probability);

assert(all(isfinite(stage1_model.training_weights)) && ...
    all(stage1_model.training_weights > 0) && ...
    abs(mean(stage1_model.training_weights) - 1) <= 1e-10);
assert(all(isfinite(stage2_model.training_weights)) && ...
    all(stage2_model.training_weights > 0) && ...
    abs(mean(stage2_model.training_weights) - 1) <= 1e-10);
assert(all(isfinite(stage1_oof_scores), 'all') && ...
    all(isfinite(stage2_oof_scores), 'all'));
assert(all(isfinite(five_state_probability), 'all') && ...
    all(five_state_probability >= 0, 'all'));
assert(isequal(size(five_state_probability), ...
    [size(example.X, 1), numel(method.five_states)]));
assert(all(ismember(string(evaluation.predicted_label), method.five_states)));

output = struct( ...
    'selected_feature_index', selected_index, ...
    'stage1_feature_index', stage1_index, ...
    'stage2_feature_index', stage2_index, ...
    'stage1_oof_scores', stage1_oof_scores, ...
    'stage2_oof_scores', stage2_oof_scores, ...
    'five_state_probability', five_state_probability, ...
    'evaluation', evaluation);

fprintf('Reference implementation path validation completed.\n');
end

function labels = stage1_labels(y)
labels = repmat("NO_NETWORK_ATTACK", numel(y), 1);
source = string(y(:));
labels(source == "REPLAY") = "REPLAY";
labels(source == "SPOOFING") = "SPOOFING";
end
