function model = train_stage2(X, y, run_id, beta_motor)
%TRAIN_STAGE2 Fit the frozen Stage 2 Bagged Trees classifier.

method = method_definition();
labels = string(y(:));
class_names = method.stage2.classes;
if ~isscalar(beta_motor) || ~ismember(beta_motor, method.stage2.allowed_beta_motor)
    error('PUBLIC_METHOD_CODE:Stage2Beta', ...
        'beta_motor must be one of the reported values: 1.0 or 1.5.');
end
if ~all(ismember(labels, class_names))
    error('PUBLIC_METHOD_CODE:Stage2Labels', ...
        'Stage 2 may be trained only on normal and physical-fault labels.');
end
if size(X, 2) < method.bagged_tree.num_predictors_to_sample
    error('PUBLIC_METHOD_CODE:PredictorCount', ...
        'The selected feature set must contain at least %d predictors.', ...
        method.bagged_tree.num_predictors_to_sample);
end
if ~all(ismember(class_names, unique(labels)))
    error('PUBLIC_METHOD_CODE:StageClassCoverage', ...
        'Each Stage 2 class must be represented in the training labels.');
end
beta_by_class = struct( ...
    'NORMAL', 1.0, ...
    'MOTOR_ACTUATOR_FAULT', beta_motor, ...
    'POSITION_SENSOR_FAULT', 1.0);
weights = compute_class_run_weights( ...
    labels, run_id, beta_by_class, method.weighting.alpha);

learner = templateTree( ...
    'MinLeafSize', method.bagged_tree.min_leaf_size, ...
    'NumVariablesToSample', method.bagged_tree.num_predictors_to_sample);
classifier = fitcensemble(X, categorical(labels, class_names, class_names), ...
    'Method', 'Bag', ...
    'NumLearningCycles', method.bagged_tree.num_learners, ...
    'Learners', learner, ...
    'Weights', weights, ...
    'ClassNames', categorical(class_names, class_names, class_names));

model = struct( ...
    'classifier', classifier, 'class_names', class_names, ...
    'training_weights', weights, 'beta_motor', beta_motor);
end
