function model = train_stage1(X, y, run_id)
%TRAIN_STAGE1 Fit the frozen Stage 1 Bagged Trees classifier.

method = method_definition();
labels = string(y(:));
if ~all(ismember(labels, method.five_states))
    error('PUBLIC_METHOD_CODE:Stage1Labels', 'Stage 1 requires five-state labels.');
end

stage_labels = repmat("NO_NETWORK_ATTACK", numel(labels), 1);
stage_labels(labels == "REPLAY") = "REPLAY";
stage_labels(labels == "SPOOFING") = "SPOOFING";
weights = compute_class_run_weights( ...
    stage_labels, run_id, method.stage1.beta_by_class, method.weighting.alpha);

model = fit_stage_classifier( ...
    X, stage_labels, method.stage1.classes, method, weights);
end

function model = fit_stage_classifier(X, labels, class_names, method, weights)
if size(X, 2) < method.bagged_tree.num_predictors_to_sample
    error('PUBLIC_METHOD_CODE:PredictorCount', ...
        'The selected feature set must contain at least %d predictors.', ...
        method.bagged_tree.num_predictors_to_sample);
end
if ~all(ismember(class_names, unique(labels)))
    error('PUBLIC_METHOD_CODE:StageClassCoverage', ...
        'Each stage class must be represented in the training labels.');
end

learner = templateTree( ...
    'MinLeafSize', method.bagged_tree.min_leaf_size, ...
    'NumVariablesToSample', method.bagged_tree.num_predictors_to_sample);
classifier = fitcensemble(X, categorical(labels, class_names, class_names), ...
    'Method', 'Bag', ...
    'NumLearningCycles', method.bagged_tree.num_learners, ...
    'Learners', learner, ...
    'Weights', weights, ...
    'ClassNames', categorical(class_names, class_names, class_names));

model = struct( ...
    'classifier', classifier, 'class_names', class_names, ...
    'training_weights', weights);
end
